<?php
require_once "lib/autoload.php";
?>
    <h2 class="voorwaarden">Algemene voorwaarden</h2>
    <p> Artikel 1<br>
        De rechtsverhouding tussen Eventologus NV, (hierna “Eventologus” genoemd), met maatschappelijke zetel te 2800 Mechelen, België, Motstraat 30, BE 0405.772.873, RPR Antwerpen, afdeling Mechelen en de klant, wordt beheerst door onderhavige algemene voorwaarden, de specifieke voorwaarden (licentievoorwaarden), de bestelbon, de facturen en de eventuele bijzondere voorwaarden (hierna gezamenlijk aangeduid als 'de Overeenkomst'). De Overeenkomst vernietigt en vervangt alle schriftelijke of mondelinge contracten, voorstellen en verbintenissen die betrekking hebben op hetzelfde voorwerp en die aan de datum van deze Overeenkomst zouden voorafgaan. De Overeenkomst heeft voorrang op de algemene en/of andere voorwaarden van de klant, zelfs indien deze bepalen dat zij als enige gelden. Afwijkingen ten opzichte van de Overeenkomst zijn slechts mogelijk na voorafgaande en schriftelijke toestemming van Eventologus. Eventologus behoudt zich het recht voor om de bepalingen van de Overeenkomst te wijzigen.
        <br><br>
        Artikel 2<br>
        De prestaties van Eventologus strekken ertoe informatie te verschaffen aan de klant via papieren dragers, diskettes, cd-roms, internet, of enige andere drager, alsook door organisatie van studiedagen en andere vormen van opleiding. De prestaties van Eventologus kunnen eveneens bestaan uit het ter beschikking stellen van advertentieruimtes of software. Hierna worden de prestaties gezamenlijk aangeduid als 'de Producten'. Voor Producten die betrekking hebben op recente ontwikkelingen in bepaalde materies waarvoor geen nieuwe informatie voorhanden is (bv. omdat er geen wetswijzigingen zijn opgetreden m.b.t. de materie), zal Eventologus geen informatie kunnen leveren. Evenwel ontslaat dit de klant niet van zijn betalingsverplichtingen. Behoudens andersluidend beding, aanvaardt de klant dat de Producten standaardproducten zijn die niet specifiek voor zijn behoeften gecreëerd werden. Bijgevolg aanvaardt de klant dat Eventologus geen garantie geeft en geen verantwoordelijkheid op zich neemt met betrekking tot het vermogen van de Producten om aan de specifieke behoeften van de klant te beantwoorden. Eventologus neemt alle redelijke maatregelen om de klant te voorzien van zo volledig en juist mogelijke Producten, evenwel zonder enige garantie in dit verband.
        <br><br>
        Artikel 3<br>
        De klant zal het advertentiemateriaal telkens drukklaar bezorgen vóór de afsluitdatum van de overeengekomen datum van publicatie. De bijkomende kosten wegens niet drukklaar afgeleverd advertentiemateriaal vallen uitsluitend ten laste van de klant. De klant draagt tevens alle risico's van beschadiging en verlies van het advertentiemateriaal tot op het ogenblik dat het advertentiemateriaal bij Eventologus afgeleverd wordt. Indien de klant een advertentieruimte niet afneemt op de overeengekomen datum van publicatie (door het niet tijdig verstrekken van het advertentiemateriaal of omwille van een andere oorzaak), dan zal deze advertentieruimte desondanks volledig aan de klant kunnen gefactureerd worden op het daartoe voorziene tijdstip. Elke advertentie zal na verschijning en per editie worden gefactureerd. Een fout of tekortkoming in de advertentie door toedoen van de klant, doet geen afbreuk aan het verschuldigd karakter van de factuur. In geval van niet-betaling is Eventologus gerechtigd om verdere inlassing van advertenties stop te zetten. Iedere wijziging van de bestelbon door de klant (tekst, plaats, data of frequentie van de advertenties) dient door Eventologus aanvaard te worden. Eventologus heeft steeds het recht om advertenties te weigeren, wijzigingen door te voeren aan de publicaties waarin de advertenties worden opgenomen (bv. vorm, formaat, rubrieken, enz.) en de advertentiemogelijkheden van haar publicaties te herzien (bv. formaten, kleur) zonder dat Eventologus hiervoor enige verantwoording verschuldigd is. Indien er sprake is van fouten of drukgebreken in hoofde van Eventologus, dan dient de klant Eventologus hiervan per aangetekende brief op de hoogte te brengen binnen 8 kalenderdagen na de publicatie van de advertentie. In dergelijk geval heeft de klant recht op een kosteloze nieuwe publicatie, met uitsluiting van enige bijkomende schadevergoeding. De klant is en blijft verantwoordelijk voor de inhoud van de advertenties. Indien er op basis van de advertentie een vordering wordt ingesteld en/of een aanspraak wordt geuit ten opzichte van Eventologus, dient de klant Eventologus de nodige bijstand te verlenen voor haar verdediging, dient hij de kosten op zich te nemen die Eventologus in dit kader dient te maken en dient hij alle door Eventologus geleden schade te vergoeden. Per publicatie zal aan de klant één gratis exemplaar van het nummer met de advertentie worden toegezonden. Elk bijkomend nummer zal worden gefactureerd. Zes maanden na de laatste publicatie van een advertentie zal het niet teruggevorderde advertentiemateriaal worden vernietigd.
        <br><br>
        Artikel 4<br>
        Commerciële documenten en aanbiedingen van Eventologus scheppen geen verbintenissen in hoofde van Eventologus. De Overeenkomst tussen Eventologus en de klant komt slechts tot stand na schriftelijke of elektronische bevestiging van de bestelling van de klant door Eventologus of bij begin van uitvoering door Eventologus.
        <br><br>
        Artikel 5<br>
        Het plaatsen van bestellingen voor Producten via de bij de klant gangbare centrale inkoopprocedure, gebeurt louter om administratieve redenen en doet geenszins afbreuk aan de integrale geldigheid van de Overeenkomst.
        <br><br>
        Artikel 6<br>
        In België zijn de prijzen van Eventologus (behoudens anders vermeld) inclusief btw en exclusief verzend- en administratiekosten. Eventologus behoudt zich te allen tijde het recht voor om voor al haar abonnementen het principe der vooruitfacturering te gebruiken tegen de op dat ogenblik geldende verkoopprijs. Eventologus behoudt zich het recht voor om de prijzen te wijzigen tijdens de duur van de Overeenkomst. Eventologus behoudt zich tevens het recht voor de factureringsperiodiciteit te wijzigen, om te schakelen van delivery-based facturering (= factuur per verzonden item) naar time-based facturering (= factuur voor een bepaalde periode) of omgekeerd, het principe van gegroepeerde facturering (= facturering van verschillende Overeenkomsten middels één factuur) toe te passen en, in het algemeen, de factureringswijze te wijzigen. Elke afwijking op de door Eventologus vastgelegde factureringsperiodiciteit moet door de klant schriftelijk worden aangevraagd en wordt slechts na uitdrukkelijk akkoord van Eventologus toegestaan. Dergelijke afwijking kan aanleiding geven tot het aanrekenen van een meerkost per op te stellen factuur.
        <br><br>
        Artikel 7<br>
        Behoudens andersluidend beding, zijn alle facturen betaalbaar binnen 30 kalenderdagen na de uitgiftedatum van de factuur. Het bedrag van elke factuur dat niet volledig betaald is op de vervaldag wordt van rechtswege en zonder voorafgaande ingebrekestelling verhoogd met een rente gelijk aan 1% per maand, waarbij elke begonnen maand beschouwd wordt als zijnde verlopen, en een forfaitaire vergoeding ten belope van 15% op het bedrag van de nog onbetaalde facturen, met een minimum van € 25,00. Bovendien is Eventologus gerechtigd de kosten voor ingebrekestelling en aanmaning (hierna 'herinneringskosten' genoemd) aan te rekenen. In zoverre de klant in gebreke blijft om één of meer uitstaande vorderingen ten aanzien van Eventologus te voldoen, kan Eventologus de uitvoering van haar Overeenkomsten met de klant opschorten tot wanneer alle uitstaande rekeningen worden aangezuiverd inclusief de toegevoegde schadevergoeding, verwijlinteresten en herinneringskosten.
        <br><br>
        Artikel 8<br>
        Alle geleverde Producten blijven eigendom van Eventologus tot volledige betaling van de hoofdsom, interesten, kosten en belastingen. De risico's zijn echter ten laste van de klant vanaf het verlaten van de magazijnen van Eventologus. Bij niet-betaling of bij het niet respecteren van één van de bepalingen van de Overeenkomst, kan Eventologus van rechtswege en zonder ingebrekestelling tot de onmiddellijke ontbinding van de Overeenkomst overgaan, onverminderd het recht om de geleverde Producten terug te nemen en een schadevergoeding te eisen.
        <br><br>
        Artikel 9<br>
        Eventologus zal alle redelijke maatregelen nemen teneinde de bestelde Producten op tijd te leveren. Indien er leveringstermijnen vermeld zijn, zijn deze slechts indicatief en vormen zij in hoofde van Eventologus geen resultaatsverbintenis. Eventologus behoudt zich het recht voor gedeeltelijke leveringen te verrichten. In geval van niet-levering van de Producten worden de eventueel door de klant betaalde voorschotten terugbetaald zonder interest of andere vergoeding.
        <br><br>
        Artikel 10<br>
        Behoudens andersluidend beding, zal de klant zijn klachten per aangetekende brief overmaken aan de klantendienst van Eventologus en dit (a) in geval van een klacht wegens zichtbare gebreken of niet-conformiteit, binnen 15 kalenderdagen na de levering van de Producten, en (b) in geval van verborgen gebreken, binnen 15 kalenderdagen na de ontdekking van dit gebrek. Het indienen van een klacht ontheft de klant niet van zijn betalingsverplichtingen. Geen aansprakelijkheid voor zichtbare en verborgen gebreken kan weerhouden worden in hoofde van Eventologus indien deze termijnen zonder ontvangst van het hierboven vermelde aangetekend schrijven zijn verstreken. De tijdige gegronde klachten van de klant zullen aanleiding geven tot de herstelling of de (gehele of gedeeltelijke) vervanging of aanvulling door Eventologus, zonder dat Eventologus daarenboven tot schadevergoeding kan gehouden zijn.
        <br><br>
        Artikel 11<br>
        Behoudens de expliciete verbintenissen aangegaan door Eventologus krachtens de Overeenkomst, is de aansprakelijkheid van Eventologus beperkt tot de aansprakelijkheid die dwingend door de wet is opgelegd. Eventologus is niet aansprakelijk voor onrechtstreekse schade, zoals verlies van data, onbeschikbaarheid van data, verlies van omzet, winstderving of elke stijging van de algemene kosten. Eventologus is evenmin aansprakelijk voor eventuele schade die voortvloeit uit het niet naleven van deze Overeenkomst door de klant, noch is Eventologus aansprakelijk voor gebreken die rechtstreeks of onrechtstreeks veroorzaakt worden door een daad van de klant of van een derde, ongeacht of deze worden veroorzaakt door een fout of nalatigheid. Indien de aansprakelijkheid van Eventologus wordt weerhouden, is Eventologus er enkel toe gehouden het Product te vervangen en, indien dit niet mogelijk is, de prijs (de jaarprijs ingeval van een abonnementsgebonden Product) terug te betalen.
        <br><br>
        Artikel 12<br>
        Elke annulering van de bestelling door de klant dient schriftelijk te gebeuren binnen 15 kalenderdagen na datum van bestelling en dient door Eventologus te worden aanvaard. In geval van annulering van de bestelling is de klant een forfaitaire schadevergoeding verschuldigd ten belope van 15% van de waarde van de bestelling. Indien de annulering betrekking heeft op advertenties is de klant een forfaitaire schadevergoeding verschuldigd ten belope van 40% van de waarde van de bestelling.
        <br><br>
        Artikel 13<br>
        Behoudens andersluidend beding, bedraagt de duur van een Overeenkomst betreffende een abonnementsgebonden Product 1 jaar. De Overeenkomst wordt stilzwijgend verlengd voor opeenvolgende periodes van telkens 1 jaar, behoudens schriftelijke opzegging tenminste 30 kalenderdagen voor het verstrijken van de lopende contractuele periode. De klant blijft echter steeds gehouden tot betaling van de laatst lopende contractuele periode en dit niettegenstaande een eventuele schriftelijke opzegging door Eventologus of de klant.
        <br><br>
        Artikel 14<br>
        De rechtbank van eerste aanleg te Brussel, de rechtbank van koophandel te Brussel, en het vredegerecht van het eerste kanton te Brussel zijn uitsluitend bevoegd voor elk geschil met betrekking tot deze Overeenkomst en Eventologus kan enkel voor deze rechtbanken worden gedagvaard. De Overeenkomst wordt beheerst door het Belgisch recht.
        <br><br>
        Artikel 15<br>
        Eventologus behoudt zich het recht voor om de kenmerken van de Producten te wijzigen en/of uit te breiden (bv. aanvullingen of bijwerkingen, cd-roms, internetservices, of andere).
        <br><br>
        Artikel 16<br>
        Elke verhuring of uitlening van het verkochte Product zonder voorafgaande en schriftelijke toestemming van Eventologus is verboden. Eventologus zal slechts toestemming tot verhuring of uitlening verlenen indien de klant aantoont dat die verhuring of uitlening gebeurt voor educatieve of culturele, niet-commerciële doeleinden en dat hij daartoe officieel door de overheid is erkend. Indien de klant het Product verhuurt of uitleent zonder voorafgaande en schriftelijke toestemming van Eventologus, is hij van rechtswege en zonder ingebrekestelling een schadevergoeding van € 250,00 per inbreuk verschuldigd, onverminderd het recht van Eventologus om een hogere schadevergoeding te vorderen of bijkomende sancties toe te passen.
        <br><br>
        Artikel 17<br>
        Behoudens de wettelijke uitzonderingen, mogen de Producten en hun inhoud niet, geheel of gedeeltelijk, verveelvoudigd, vertaald, aangepast, gereproduceerd of opgeslagen worden in enige vorm of op enige wijze, noch mogen de Producten en hun inhoud, geheel of gedeeltelijk, medegedeeld of doorgegeven worden aan het publiek in enige vorm of op enige wijze (zoals, maar niet beperkt tot, elektronische en mechanische wijze) zonder voorafgaande en schriftelijke toestemming van de rechthebbende of Eventologus.
        <br><br>
        Artikel 18<br>
        De door de klant verstrekte gegevens worden opgenomen in het bestand van Eventologus. Deze gegevens zullen gebruikt worden met het oog op het voeren van informatie- of promotiecampagnes in verband met de door Eventologus aangeboden Producten en/of in het kader van de contractuele relatie tussen de klant en Eventologus. De contactgegevens van de klant kunnen mits uitdrukkelijke toestemming van de klant eveneens door Eventologus gebruikt worden voor direct marketing doeleinden en mits uitdrukkelijke toestemming overgemaakt worden aan derden (zakelijke partners, dochterondernemingen) voor direct marketing doeleinden. Zonder uitdrukkelijke toestemming zullen de gegevens voor deze doeleinden niet gebruikt of doorgegeven worden.
        <br><br>
        In het kader van de contractuele relatie tussen de klant en Eventologus zullen de gegevens van de klant zullen uitsluitend verwerkt worden door Eventologus en de door haar aangestelde verwerkers, met wie de nodige contractuele afspraken gemaakt zijn. Eventologus zal de gegevens niet buiten de Europese Economische Ruimte opslaan zonder de klant hiervan voorafgaand te informeren onder meer omtrent de passende waarborgen inzake de doorgifte en indien nodig de toestemming van de klant verkrijgen hiervoor.
        <br><br>
        Eventologus zal zich inspannen alle redelijke technische en organisatorische maatregelen te nemen ter bescherming en beveiliging van de gegevens tegen toevallige of ongeoorloofde vernietiging, tegen toevallig verlies, evenals tegen de wijziging van of de toegang tot, en iedere andere niet toegelaten verwerking van persoonsgegevens, rekening houdend met de stand van de techniek. Gegevens die niet langer nodig of nuttig zijn, zullen gewist worden.
        <br><br>
        De klant kan steeds om inzage in, verbetering, wissing of overdracht van zijn gegevens vragen en zich verzetten tegen gebruik van de gegevens voor direct marketing. Deze aanvraag is kosteloos, uitgezonderd indien binnen een termijn van zes maanden reeds eerder een verzoek of een vraag tot bijkomende kopieën werd geformuleerd door de betrokkene, in welk geval Eventologus het recht heeft om een redelijke vergoeding aan te rekenen op basis van de administratieve kosten die het gevolg zijn van het nieuwe verzoek. Nadere inlichtingen kunnen teruggevonden worden in de Privacy Policy van Eventologus via https://www.wolterskluwer.be/corporate/nl/privacy, kunnen bekomen worden via https://www.wolterskluwer.be/corporate/nl/gdpr en de Gegevensbeschermingsautoriteit, bij wie de klant steeds het recht heeft klacht in te dienen.
        <br><br>
        Artikel 19<br>
        Bepaalde Producten waarbij de informatie of software o.a. via een diskette, cd-rom of internet ter beschikking van de klant gesteld wordt, zijn naast onderhavige algemene voorwaarden onderworpen aan specifieke voorwaarden. Deze specifieke voorwaarden kunnen geraadpleegd worden op de website van Eventologus of kunnen op eenvoudig verzoek bij Eventologus bekomen worden. In geval van tegenstrijdigheid tussen onderhavige algemene voorwaarden en de specifieke voorwaarden zullen deze laatste voorrang hebben.
        <br><br>
        Artikel 20<br>
        De klant mag de Overeenkomst niet overdragen aan een derde behoudens voorafgaande schriftelijke toestemming van Eventologus.
        <br><br>
        Artikel 21<br>
        De partijen kunnen niet aansprakelijk worden gesteld voor vertragingen of gebreken in de uitvoering van de Overeenkomst als deze vertragingen of gebreken het gevolg zijn van feiten of omstandigheden die onafhankelijk zijn van de wil van één van de partijen, die niet te voorzien zijn en die niet vermeden kunnen worden (bv. gehele of gedeeltelijke stagnatie van het vervoerapparaat, ziekte onder het personeel van Eventologus, telecommunicatieproblemen, bedrijfsstoornis of tekortkomingen vanwege leveranciers van Eventologus). Op straffe van verval, is de partij die zich wil beroepen op dergelijke feiten of omstandigheden ertoe gehouden deze feiten of omstandigheden zo snel mogelijk schriftelijk aan de andere partij bekend te maken, alles in het werk te stellen om de duur ervan tot het strikte minimum te beperken en de andere partij er eveneens schriftelijk van te verwittigen als deze feiten of omstandigheden beëindigd zijn. Indien deze feiten of omstandigheden langer dan 3 maanden duren, dan kan elke partij de Overeenkomst van rechtswege en per aangetekende brief opzeggen zonder dat daardoor enige schadeloosstelling verschuldigd zou zijn.
        <br><br>
        Artikel 22<br>
        De eventuele nietigheid van één van de bepalingen van de Overeenkomst zal geenszins invloed hebben op de geldigheid van de andere clausules ondanks de nietigheid van de betwiste clausule. De partijen zullen alles in het werk stellen om, in onderlinge overeenstemming, de nietige clausule te vervangen door een geldige clausule met dezelfde of grotendeels dezelfde economische impact als de nietige clausule.
        <br><br>
        Artikel 23<br>
        Het niet opeisen van een recht of het niet toepassen van een sanctie door Eventologus houdt geenszins een afstand van recht in.</p>
<?php
print LoadTemplate("scroll_to_top");
print LoadTemplate("basic_footer");
?>